"""
Django settings for aivaid project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ROOT_PATH = os.path.dirname(__file__)
GEOIP_PATH =os.path.join(BASE_DIR, 'geoip')
# GEOIP_CITY =os.path.join(BASE_DIR, 'geoip/GeoLite2-City.mmdb')



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ti&tsda+7mf*2r=ajy#=op!y#23_53sr@p0dm-2!uulad8lnx2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aivaidapp',
    'doctorapp',
    'patientapp',
    'apiapp',
    'superuser',
    'social_django',
    'rest_framework',
    'rest_framework.authtoken',

]
#
# MIDDLEWARE_CLASSES = [
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.locale.LocaleMiddleware',
#      'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#
# ]

MIDDLEWARE_CLASSES = (
   'django.contrib.sessions.middleware.SessionMiddleware',
   'django.middleware.locale.LocaleMiddleware',
   'django.middleware.common.CommonMiddleware',
)

ROOT_URLCONF = 'aivaid.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # <- Here
                'social_django.context_processors.login_redirect',  # <- Here
                'django.template.context_processors.i18n',


            ],
        },
    },
]

WSGI_APPLICATION = 'aivaid.wsgi.application'




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'webtuni1_aivaid',
        'USER': 'webtuni1_aivaid',
        'PASSWORD': 'asdfghjkl',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}



AUTHENTICATION_BACKENDS = (
    'social_core.backends.open_id.OpenIdAuth',  # for Google authentication
    'social_core.backends.google.GoogleOpenId',  # for Google authentication
    'social_core.backends.google.GoogleOAuth2',  # for Google authentication
    'social_core.backends.github.GithubOAuth2',  # for Github authentication
    'social_core.backends.facebook.FacebookOAuth2',  # for Facebook authentication

    # 'phone_login.backends.phone_backend.PhoneBackend', #login with phone

    'django.contrib.auth.backends.ModelBackend',
)



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    )
}


# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
from django.utils.translation import gettext_lazy as _


# TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

LOGIN_REDIRECT_URL = 'start-checkup'



STATIC_URL = '/static/'
STATIC_ROOT =os.path.join(BASE_DIR, 'static/')
# STATIC_ROOT =''
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static/')]

#

MEDIA_URL = 'uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads/')


LOCALE_PATHS = (
   os.path.join(BASE_DIR, 'locale/'),
)

ugettext = lambda s: s


LANGUAGES = (
('ar', ugettext('Arabic')),
('en', ugettext('English')),
)


MULTILINGUAL_LANGUAGES = (
    "en-us",
    "ar-ae",
)

LANGUAGE_CODE = 'en'

#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'email-smtp.us-east-1.amazonaws.com'

#EMAIL_PORT =587 #465# Gmail SMTP port for TLS
#EMAIL_USE_TLS = True
#EMAIL_HOST_USER = 'ses-smtp-user.20171026-174643-at-096599521522'
#EMAIL_HOST_USER = 'AKIAJ2NFRQSWQ3DYOGJQ'
#EMAIL_HOST_PASSWORD = 'AgQzRxtD/XcfwDL7WKo1B8sFfjLZb1Tit8fSua11/awN'
#DEFAULT_FROM_EMAIL = 'info@aivaid.com'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'email-smtp.us-east-1.amazonaws.com'

EMAIL_PORT =587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'AKIAIHK733BZJSOKRFSA'
EMAIL_HOST_PASSWORD = 'BNVFAKk9+hXVBoue1ggscn4KnvkxTvFf4Gf8NFwk3vyh'
DEFAULT_FROM_EMAIL = 'help@webtunix.ai'







SOCIAL_AUTH_GOOGLE_OAUTH2_KEY ='900124596671-b4p6e49j9u4hog3cbg3i5kh071d1137p.apps.googleusercontent.com'  #Paste CLient Key
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'BZU1YskFsCq8TXrPK5JVzJBb' #Paste Secret Key

SOCIAL_AUTH_GITHUB_KEY = 'a79b6aff0042c7ce2341'#Paste Client ID
SOCIAL_AUTH_GITHUB_SECRET ='842da0b1851b918228c5f40d8713ef46889e7194' #Paste Secret Key


SOCIAL_AUTH_FACEBOOK_KEY = '1806572802783534'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = '575e787d373f8b6b9cb95914e4e6222a'  # App Secret


SOCIAL_AUTH_TWITTER_KEY = '9TD12xahCWCDdyLzpmw61GSM9'
SOCIAL_AUTH_TWITTER_SECRET = 'mwtdcUe4uOvvJjDk2AuQ9Mq2xiHPw3740m5iGLf6hwg3B4TNSx'
