# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='accept_terms_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_terms', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'accept_terms_db',
            },
        ),
        migrations.CreateModel(
            name='clinic_details_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ctype', models.CharField(blank=True, max_length=100, null=True)),
                ('Cname', models.CharField(blank=True, max_length=1000, null=True)),
                ('Ctitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('Cfee', models.CharField(blank=True, max_length=1000, null=True)),
                ('Online_Cfee', models.CharField(blank=True, max_length=1000, null=True)),
                ('Cphone01', models.CharField(blank=True, max_length=1000, null=True)),
                ('Cphone02', models.CharField(blank=True, max_length=1000, null=True)),
                ('Cstate', models.CharField(blank=True, max_length=1000, null=True)),
                ('Ccity', models.CharField(blank=True, max_length=1000, null=True)),
                ('Caddress', models.CharField(blank=True, max_length=1000, null=True)),
                ('Cphotos', models.FileField(blank=True, null=True, upload_to='clinic_profile')),
                ('sunday_appt_time1', models.CharField(blank=True, max_length=1000, null=True)),
                ('sunday_appt_time2', models.CharField(blank=True, max_length=1000, null=True)),
                ('monday_appt_time1', models.CharField(blank=True, max_length=1000, null=True)),
                ('monday_appt_time2', models.CharField(blank=True, max_length=1000, null=True)),
                ('tuesday_appt_time1', models.CharField(blank=True, max_length=1000, null=True)),
                ('tuesday_appt_time2', models.CharField(blank=True, max_length=1000, null=True)),
                ('wednesday_appt_time1', models.CharField(blank=True, max_length=1000, null=True)),
                ('wednesday_appt_time2', models.CharField(blank=True, max_length=1000, null=True)),
                ('thursday_appt_time1', models.CharField(blank=True, max_length=1000, null=True)),
                ('thursday_appt_time2', models.CharField(blank=True, max_length=1000, null=True)),
                ('friday_appt_time1', models.CharField(blank=True, max_length=1000, null=True)),
                ('friday_appt_time2', models.CharField(blank=True, max_length=1000, null=True)),
                ('saturday_appt_time1', models.CharField(blank=True, max_length=1000, null=True)),
                ('saturday_appt_time2', models.CharField(blank=True, max_length=1000, null=True)),
                ('Cproof', models.FileField(blank=True, null=True, upload_to='clinic_idproof')),
                ('Cmedproof', models.FileField(blank=True, null=True, upload_to='clinic_idproof')),
                ('doctor_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinic_details_db',
            },
        ),
        migrations.CreateModel(
            name='clinic_pic_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cphotos1', models.FileField(blank=True, null=True, upload_to='clinic_profile')),
                ('Cphotos2', models.FileField(blank=True, null=True, upload_to='clinic_profile')),
                ('Cphotos3', models.FileField(blank=True, null=True, upload_to='clinic_profile')),
                ('Cphotos4', models.FileField(blank=True, null=True, upload_to='clinic_profile')),
                ('Cphotos5', models.FileField(blank=True, null=True, upload_to='clinic_profile')),
                ('Cphotos6', models.FileField(blank=True, null=True, upload_to='clinic_profile')),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aivaidapp.clinic_details_db')),
                ('doctor_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinic_pic_db',
            },
        ),
        migrations.CreateModel(
            name='Contact_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Contact_db',
            },
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_Name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='disease_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'disease_db',
            },
        ),
        migrations.CreateModel(
            name='doctor_appointment_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('mobile', models.CharField(max_length=100, unique=True)),
                ('birtdate', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_appointment', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.CharField(blank=True, max_length=100, null=True)),
                ('end_time', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('problmes', models.CharField(blank=True, max_length=1000, null=True)),
                ('type_what_you_want', models.CharField(blank=True, max_length=1000, null=True)),
                ('doctor_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_appointment_db',
            },
        ),
        migrations.CreateModel(
            name='doctor_patient_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=1000)),
                ('birthdate', models.CharField(max_length=1000)),
                ('age', models.CharField(max_length=1000)),
                ('mobile', models.CharField(max_length=1000)),
                ('martial_status', models.CharField(max_length=1000)),
                ('blood_group', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('injury', models.CharField(max_length=1000)),
                ('upload_profile', models.FileField(upload_to='patient_profile')),
                ('doctor_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_patient_db',
            },
        ),
        migrations.CreateModel(
            name='doctor_patient_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('descrition', models.CharField(blank=True, max_length=1000, null=True)),
                ('Disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aivaidapp.disease_db')),
                ('doctor_patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aivaidapp.doctor_patient_db')),
                ('doctor_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_patient_report',
            },
        ),
        migrations.CreateModel(
            name='doctor_profile_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udob', models.CharField(blank=True, max_length=100, null=True)),
                ('umobile', models.CharField(blank=True, max_length=1000, null=True)),
                ('ugender', models.CharField(blank=True, max_length=1000, null=True)),
                ('state', models.CharField(blank=True, max_length=1000, null=True)),
                ('selectcity', models.CharField(blank=True, max_length=1000, null=True)),
                ('uregNumber', models.CharField(blank=True, max_length=1000, null=True)),
                ('ucounsil', models.CharField(blank=True, max_length=1000, null=True)),
                ('regyear', models.CharField(blank=True, max_length=1000, null=True)),
                ('selectdegree', models.CharField(blank=True, max_length=1000, null=True)),
                ('uinstitute', models.CharField(blank=True, max_length=1000, null=True)),
                ('degreecompletion', models.CharField(blank=True, max_length=1000, null=True)),
                ('uexperience01', models.CharField(blank=True, max_length=1000, null=True)),
                ('uexperience_month', models.CharField(blank=True, max_length=1000, null=True)),
                ('uexperience02', models.CharField(blank=True, max_length=1000, null=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='doctor_profile')),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobile_verify', models.CharField(default=0, max_length=10)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('admin_verify', models.CharField(default=0, max_length=10)),
                ('doctor_idproof', models.FileField(blank=True, null=True, upload_to='doctor_idproof')),
                ('doctor_idproof2', models.FileField(blank=True, null=True, upload_to='doctor_idproof')),
                ('doctor_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_profile_db',
            },
        ),
        migrations.CreateModel(
            name='doctor_schedule_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=1000)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=1000)),
                ('patient_time', models.CharField(max_length=1000)),
                ('active_inactive', models.CharField(max_length=1000)),
                ('doctor_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_schedule_db',
            },
        ),
        migrations.CreateModel(
            name='doctor_Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=10000, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('discount', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.CharField(blank=True, default='2019-06-28', max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_Services',
            },
        ),
        migrations.CreateModel(
            name='instamojo_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('payment_request_id', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, default='2019-06-28', max_length=100)),
            ],
            options={
                'db_table': 'instamojo_payment',
            },
        ),
        migrations.CreateModel(
            name='instamojo_payment_done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('payment_request_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=500)),
                ('payment_id', models.CharField(max_length=255, unique=True)),
                ('doctor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, default='2019-06-28', max_length=100)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instamojo_payment_done',
            },
        ),
        migrations.CreateModel(
            name='messages_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(blank=True, max_length=10, null=True)),
                ('message', models.CharField(blank=True, max_length=10000, null=True)),
                ('msg_sender', models.CharField(blank=True, max_length=10, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages_db',
            },
        ),
        migrations.CreateModel(
            name='notification_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('notification', models.CharField(blank=True, max_length=100, null=True)),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('date_1', models.CharField(blank=True, default='2019-06-28', max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_Db',
            },
        ),
        migrations.CreateModel(
            name='patient_appointment_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_appointment', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.CharField(blank=True, max_length=100, null=True)),
                ('end_time', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('problmes', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, max_length=1000, null=True)),
                ('treatment', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment', models.CharField(blank=True, max_length=100, null=True)),
                ('type_what_you_want', models.CharField(blank=True, max_length=1000, null=True)),
                ('confirm', models.CharField(default=0, max_length=1000)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aivaidapp.clinic_details_db')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aivaidapp.doctor_profile_db')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_appointment_db',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, default='2019-06-28', max_length=100)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='questions_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_name', models.CharField(max_length=1000)),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aivaidapp.disease_db')),
            ],
            options={
                'db_table': 'questions_db',
            },
        ),
        migrations.CreateModel(
            name='reports_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('disease', models.CharField(blank=True, max_length=100, null=True)),
                ('prescription', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_Db',
            },
        ),
        migrations.CreateModel(
            name='review_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('rating1', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.CharField(blank=True, default='2019-06-28', max_length=100)),
                ('doctor_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_db',
            },
        ),
        migrations.CreateModel(
            name='symptoms_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_name', models.CharField(max_length=100, unique=True)),
                ('pkl_file', models.FileField(upload_to='pkl_model')),
            ],
            options={
                'db_table': 'symptoms_db',
            },
        ),
        migrations.CreateModel(
            name='symptoms_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_type_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'symptoms_type',
            },
        ),
        migrations.CreateModel(
            name='user_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('myfile', models.FileField(blank=True, null=True, upload_to='patient_profile')),
                ('blood_group', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('height_cm', models.CharField(blank=True, max_length=100, null=True)),
                ('height_feet', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('body_mass_index', models.CharField(blank=True, max_length=100, null=True)),
                ('results', models.CharField(blank=True, max_length=100, null=True)),
                ('your_symptoms', models.CharField(blank=True, max_length=1000, null=True)),
                ('Recently_Visited_Locations', models.CharField(blank=True, max_length=1000, null=True)),
                ('auth_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_db',
            },
        ),
        migrations.CreateModel(
            name='user_medical_record_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medrecord', models.FileField(blank=True, null=True, upload_to='medrecord')),
                ('rtitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('rname', models.CharField(blank=True, max_length=1000, null=True)),
                ('rselect_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('rrecord', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_medical_record_db',
            },
        ),
        migrations.AddField(
            model_name='symptoms_db',
            name='symptoms_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aivaidapp.symptoms_type'),
        ),
        migrations.AddField(
            model_name='questions_db',
            name='symptoms_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aivaidapp.symptoms_db'),
        ),
        migrations.AddField(
            model_name='disease_db',
            name='symptoms_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aivaidapp.symptoms_db'),
        ),
    ]
