# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aivaidapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms_db',
            name='symptoms_type_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='aivaidapp.symptoms_type'),
        ),
    ]
