# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aivaidapp', '0002_auto_20190628_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptoms_db',
            name='symptoms_type_id',
        ),
    ]
