# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('slug', models.SlugField(max_length=2000)),
                ('image', models.ImageField(upload_to='picfolder')),
                ('categories', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=50000)),
                ('meta_title', models.CharField(max_length=2000)),
                ('meta_keyword', models.CharField(max_length=2000)),
                ('meta_description', models.CharField(max_length=2000)),
                ('date', models.CharField(blank=True, default='2018-08-29', max_length=100)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000)),
                ('meta_title', models.CharField(max_length=1000)),
                ('meta_keyword', models.CharField(max_length=1000)),
                ('meta_description', models.CharField(max_length=1000)),
                ('date', models.CharField(blank=True, default='2018-08-29', max_length=100)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
